export const groups = [
  { group_id: 1, group_name: "Alpha Team", leader: "Alice Johnson" },
  { group_id: 2, group_name: "Beta Squad", leader: "Bob Smith" },
  { group_id: 3, group_name: "Gamma Crew", leader: "Carol White" },
  { group_id: 4, group_name: "Delta Force", leader: "David Brown" },
  { group_id: 5, group_name: "Epsilon Unit", leader: "Eve Davis" },
  { group_id: 6, group_name: "Zeta League", leader: "Frank Wilson" },
  { group_id: 7, group_name: "Theta Circle", leader: "Grace Martinez" },
  { group_id: 8, group_name: "Lambda Pack", leader: "Henry Anderson" },
  { group_id: 9, group_name: "Omega Society", leader: "Isabella Taylor" },
  { group_id: 10, group_name: "Sigma Alliance", leader: "Jack Thomas" },
  { group_id: 11, group_name: "Kappa Order", leader: "Karen Lee" },
  { group_id: 12, group_name: "Rho Coalition", leader: "Larry Walker" },
  { group_id: 13, group_name: "Mu Fellowship", leader: "Megan Harris" },
  { group_id: 14, group_name: "Nu Brotherhood", leader: "Nathan Robinson" },
  { group_id: 15, group_name: "Pi Network", leader: "Olivia Clark" },
  { group_id: 111, group_name: "Alpha Team", leader: "Alice Johnson" },
  { group_id: 211, group_name: "Beta Squad", leader: "Bob Smith" },
  { group_id: 311, group_name: "Gamma Crew", leader: "Carol White" },
  { group_id: 411, group_name: "Delta Force", leader: "David Brown" },
  { group_id: 511, group_name: "Epsilon Unit", leader: "Eve Davis" },
  { group_id: 611, group_name: "Zeta League", leader: "Frank Wilson" },
  { group_id: 711, group_name: "Theta Circle", leader: "Grace Martinez" },
  { group_id: 811, group_name: "Lambda Pack", leader: "Henry Anderson" },
  { group_id: 911, group_name: "Omega Society", leader: "Isabella Taylor" },
  { group_id: 1011, group_name: "Sigma Alliance", leader: "Jack Thomas" },
  { group_id: 1111, group_name: "Kappa Order", leader: "Karen Lee" },
  { group_id: 1211, group_name: "Rho Coalition", leader: "Larry Walker" },
  { group_id: 1311, group_name: "Mu Fellowship", leader: "Megan Harris" },
  { group_id: 1411, group_name: "Nu Brotherhood", leader: "Nathan Robinson" },
  { group_id: 1511, group_name: "Pi Network", leader: "Olivia Clark" },
];

const courseProviders = [
  "ዩዳሲቲ (Udacity)",        // Focus: AI, Self-driving cars, Tech Nanodegrees
  "ዩዳሚ (Udemy)",           // Wide range of affordable tech/coding courses
  "ኮርሴራ (Coursera)",       // University-certified courses (with some financial aid)
  "ኢዲኤክስ (edX)",          // Harvard/MIT courses (free audit option)
  "ኮድ አካደሚ (Codecademy)",  // Interactive coding platform
  "የኢትዮጵያ አይሲቲ ኢንስቲትዩት (Ethiopian ICT Institute)", // Local tech courses
  "አልክስ ኢትዮጵያ (ALX Ethiopia)",  // Software engineering training
  "ጎግል የስልጠና ፕሮግራም (Google Digital Garage)",
  "ዋትስአፕ (W3Schools)",     // Free web development tutorials
  "ኬን አካደሚ (Khan Academy)", // Free STEM fundamentals
  "ፍሪኮድካምፕ (freeCodeCamp)", // Free coding curriculum
  "ስክልራ (Skillshare)",     // Creative/design courses
  "ዩኒቨርሲቲ ድጋፍ (University Partnerships)" // e.g., AAU online courses
];



export const users = [
  {
    event_id: 1,
    firstName: "Alice",
    lastName: "Johnson",
    phone: "0912345671",
    role: "Admin",
    bureau: "Admin Bureau",
  },
  {
    event_id: 2,
    firstName: "Bob",
    lastName: "Smith",
    phone: "0912345672",
    role: "Coordinator",
    bureau: "Bureau of Coordination",
  },
  {
    event_id: 3,
    firstName: "Carol",
    lastName: "Taylor",
    phone: "0912345673",
    role: "Manager",
    bureau: "Management",
  },
  {
    event_id: 4,
    firstName: "David",
    lastName: "Brown",
    phone: "0912345674",
    role: "Coordinator",
    bureau: "Bureau of Coordination",
  },
  {
    event_id: 5,
    firstName: "Eve",
    lastName: "Davis",
    phone: "0912345675",
    role: "Admin",
    bureau: "Admin Bureau",
  },
  {
    event_id: 6,
    firstName: "Frank",
    lastName: "Wilson",
    phone: "0912345676",
    role: "Manager",
    bureau: "Finance Bureau",
  },
  {
    event_id: 7,
    firstName: "Grace",
    lastName: "Lee",
    phone: "0912345677",
    role: "Coordinator",
    bureau: "Bureau of Coordination",
  },
  {
    event_id: 8,
    firstName: "Henry",
    lastName: "Martinez",
    phone: "0912345678",
    role: "Admin",
    bureau: "Admin Bureau",
  },
  {
    event_id: 9,
    firstName: "Ivy",
    lastName: "Thomas",
    phone: "0912345679",
    role: "Manager",
    bureau: "Operations",
  },
  {
    event_id: 10,
    firstName: "Jack",
    lastName: "Moore",
    phone: "0912345680",
    role: "Coordinator",
    bureau: "Bureau of Coordination",
  },
  {
    event_id: 11,
    firstName: "Kathy",
    lastName: "Anderson",
    phone: "0912345681",
    role: "Admin",
    bureau: "Admin Bureau",
  },
  {
    event_id: 12,
    firstName: "Leo",
    lastName: "White",
    phone: "0912345682",
    role: "Manager",
    bureau: "Resource Management",
  },
  {
    event_id: 13,
    firstName: "Mia",
    lastName: "Harris",
    phone: "0912345683",
    role: "Coordinator",
    bureau: "Bureau of Coordination",
  },
  {
    event_id: 14,
    firstName: "Noah",
    lastName: "Clark",
    phone: "0912345684",
    role: "Admin",
    bureau: "Admin Bureau",
  },
  {
    event_id: 15,
    firstName: "Olivia",
    lastName: "Lewis",
    phone: "0912345685",
    role: "Manager",
    bureau: "Human Resources",
  },
];

export const events = [
  {
    event_id: 1,
    title: "React Summit 2023",
    subTitle: "ReactJS Global Meetup",
    description:
      "An international meetup on React ecosystem and performance optimization.",
    placeOfEvent: "Millennium Hall",
    sector: "Kirkos",
    noOfParticipant: "150",
    state: "upcomming",
    date: "2023-06-10",
    photos: ["bole_coorider.jpg_large", "track1.png", "assigntask1.webp"],
  },
  {
    event_id: 2,
    title: "AI for Africa 2023",
    subTitle: "Artificial Intelligence Conference",
    description: "Discussing the future of AI in African development.",
    placeOfEvent: "Skylight Hotel",
    sector: "Bole",
    noOfParticipant: "250",
    state: "done",
    date: "2023-09-22",
    photos: ["bole_coorider.jpg_large", "track1.png"],
  },
  {
    event_id: 3,
    title: "Ethiopian Developers Day",
    subTitle: "Tech Expo 2023",
    description: "Exhibition of tech innovations by Ethiopian developers.",
    placeOfEvent: "Science Museum",
    sector: "Yeka",
    noOfParticipant: "500",
    state: "done",
    date: "2023-12-01",
    photos: ["bole_coorider.jpg_large", "track1.png"],
  },
  {
    event_id: 4,
    title: "Cybersecurity Forum",
    subTitle: "Defending the Digital Frontier",
    description: "Workshops and panels on cybersecurity threats and solutions.",
    placeOfEvent: "UN-ECA",
    sector: "Arada",
    noOfParticipant: "320",
    state: "done",
    date: "2024-01-15",
    photos: ["bole_coorider.jpg_large", "track1.png", "cyber3.jpg"],
  },
  {
    event_id: 5,
    title: "Mobile Dev Camp",
    subTitle: "Flutter & React Native",
    description: "Two-day camp for mobile developers across Ethiopia.",
    placeOfEvent: "AAU ICT Park",
    sector: "Akaki Kality",
    noOfParticipant: "180",
    state: "done",
    date: "2024-02-20",
    photos: ["bole_coorider.jpg_large", "track1.png"],
  },
  {
    event_id: 6,
    title: "She Codes Hackathon",
    subTitle: "Women in Tech",
    description: "A hackathon celebrating women coders in Ethiopia.",
    placeOfEvent: "Orbit Innovation Hub",
    sector: "Nifas Silk",
    noOfParticipant: "90",
    state: "done",
    date: "2024-03-08",
    photos: ["bole_coorider.jpg_large", "track1.png"],
  },
  {
    event_id: 7,
    title: "E-Gov Summit",
    subTitle: "Digital Governance",
    description: "Conference on building digital public infrastructure.",
    placeOfEvent: "Friendship Hotel",
    sector: "Lideta",
    noOfParticipant: "210",
    state: "done",
    date: "2024-03-30",
    photos: ["bole_coorider.jpg_large", "track1.png"],
  },
  {
    event_id: 8,
    title: "NextGen Coders Bootcamp",
    subTitle: "Youth Coding Program",
    description: "Bootcamp for high school students interested in coding.",
    placeOfEvent: "Tewahedo Tech Hub",
    sector: "Gullele",
    noOfParticipant: "120",
    state: "done",
    date: "2024-04-12",
    photos: ["bole_coorider.jpg_large", "track1.png"],
  },
  {
    event_id: 9,
    title: "GreenTech Expo",
    subTitle: "Sustainable Tech Solutions",
    description: "Exploring environmentally friendly tech solutions.",
    placeOfEvent: "Ghion Hotel",
    sector: "Addis Ketema",
    noOfParticipant: "75",
    state: "done",
    date: "2024-05-05",
    photos: ["bole_coorider.jpg_large", "track1.png"],
  },
  {
    event_id: 10,
    title: "DevFest Ethiopia",
    subTitle: "GDG Annual Conference",
    description: "The biggest Google Developers Group event in Ethiopia.",
    placeOfEvent: "AAU Main Campus",
    sector: "SNNP",
    noOfParticipant: "600",
    state: "done",
    date: "2024-06-01",
    photos: ["bole_coorider.jpg_large", "track1.png"],
  },

  // Upcoming events...
  {
    event_id: 11,
    title: "Tech Conference 2024",
    subTitle: "Tech Conference 2024",
    description: "A conference about React and AI.",
    placeOfEvent: "Friendship International Center",
    sector: "Bole",
    noOfParticipant: "300",
    state: "upcomming",
    date: "2024-11-15",
    photos: ["bole_coorider.jpg_large", "track1.png"],
  },
  {
    event_id: 12,
    title: "Blockchain for Finance",
    subTitle: "Secure Transactions",
    description: "Conference on blockchain-based financial solutions.",
    placeOfEvent: "Radisson Blu",
    sector: "Kirkos",
    noOfParticipant: "200",
    state: "upcomming",
    date: "2024-11-28",
    photos: ["bole_coorider.jpg_large", "track1.png"],
  },
  {
    event_id: 13,
    title: "Ethiopia Startup Forum",
    subTitle: "Entrepreneurs Meet Investors",
    description: "Pitching platform for startups and investors.",
    placeOfEvent: "Skylight Hotel",
    sector: "Bole",
    noOfParticipant: "350",
    state: "upcomming",
    date: "2024-12-10",
    photos: ["bole_coorider.jpg_large", "track1.png"],
  },
  {
    event_id: 14,
    title: "GIS & Smart Cities",
    subTitle: "Urban Innovation",
    description: "Using GIS tech to plan better cities.",
    placeOfEvent: "Ministry of Innovation Hall",
    sector: "Arada",
    noOfParticipant: "160",
    state: "upcomming",
    date: "2025-01-20",
    photos: ["bole_coorider.jpg_large", "track1.png"],
  },
  {
    event_id: 15,
    title: "AgriTech Solutions",
    subTitle: "Digital Farming",
    description: "Empowering farmers with digital tools.",
    placeOfEvent: "MoA Conference Center",
    sector: "Lemi Kura",
    noOfParticipant: "190",
    state: "upcomming",
    date: "2025-05-05",
    photos: ["bole_coorider.jpg_large", "track1.png"],
  },
];

export const slides = [
  {
    event_id: 1,
    image:
      "https://images.unsplash.com/photo-1517048676732-d65bc937f952?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    title: "discoverTechEvents", // Reusing your existing text
    description: "heroDescription",
  },
  {
    event_id: 2,
    image: "/images/abyi.jpeg",
    // "https://images.unsplash.com/photo-1549692520-acc6669e2f0c?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    title: "innovateAndConnect", // New text for second slide
    description: "findYourNextBigIdea", // New text for second slide
  },
  {
    event_id: 3,
    image:
      "https://images.unsplash.com/photo-1549692520-acc6669e2f0c?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    title: "learnFromExperts", // New text for third slide
    description: "exploreWorkshopsAndSeminars", // New text for third slide
  },
];

export const sectors = [
  "አራዳ ክፍለ ከተማ ",
  "ቦሌ ክፍለ ከተማ",
  "የካ ክፍለ ከተማ",
  "አዲስ ከተማ ክፍለ ከተማ",
  "ልደታ ክፍለ ከተማ",
  "ቂርቆስ ክፍለ ከተማ",
  "ኮልፌ ቀራንዮ ክፍለ ከተማ",
  "አቃቂ ቃሊቲ ክፍለ ከተማ",
  "ንፋስ ስልክ ላፍቶ ክፍለ ከተማ",
  "ጉለሌ ክፍለ ከተማ",
  "ለሚ ኩራ ክፍለ ከተማ",
  "አዲስ አበባ ኢኖቬሽን እና ቴክኖሎጂ ልማት ቢሮ",
  "አዲስ አበባ ከተማ ምክር ቤት",
  "ከንቲባ ጽ/ቤት",
  "ስራ አስኪያጅ ጽ/ቤት",
  "ስራና ክህሎት ቢሮ",
  "ኢንዱስትሪ ልማት ቢሮ",
  "ሰላምና ጸጥታ አስተዳደር ቢሮ",
  "ፍትህ ቢሮ",
  "መሬት ልማትና አስተዳደር ቢሮ",
  "ቤቶች ልማት አስተዳደር ቢሮ",
  "ቤቶች ልማት ኮርፖሬሽን",
  "ዲዛይንና ግንባታ ስራዎች ቢሮ",
  "ግንባታ ፍቃድና ቁጥጥር ባለስልጣን",
  "ከተማ ውበትና አረንጓዴ ልማት ቢሮ",
  "ሴቶች፣ህጻናትና ማህበራዊ ጉዳይ ቢሮ",
  "ባህል፣ኪነጥበብና ቱሪዝም ቢሮ",
  "ኮሚኒኬሽን ቢሮ",
  "ፕላንና ልማት ቢሮ",
  "አርሶ አደርና ከተማ ግብርና ልማት ኮሚሽን",
  "አካባቢ ጥበቃ ባለስልጣን",
  "ህብረተሰብ ተሳትፎና በጎ ፍቃድ ማስተባበሪያ ኮሚሽን",
  "መሬት ይዞታ ምዝገባና መረጃ ኤጀንሲ",
  "መንግስት የግዥና ንብረት ማሰወገድ አገልግሎት",
  "ምግበና መድኃኒት አስተዳደር ባለስልጣን",
  "ጽዳት አስተዳደር ኤጀንሲ",
  "ህብረት ስራ ኤጀንሲ",
  "ሲቭል ምዝገባና ነዋሪነት አገልግሎት ኤጀንሲ",
  "ደንብ ማስከበር ባለስልጣን",
  "ምገባ ኤጀንሲ",
  "አዲስ አበባ አመራር አካዳሚ",
  "ጉለሌ እጽዋት ማእከል",
  "መንግስት ንብረት አስተዳደር ባለስልጣን",
  "ጤና ቢሮ",
  "ትምህርት ቢሮ",
  "ውሃና ፍሳሽ ባለስልጣን",
  "ፐብሊክ ሰርቪስ የሰው ሃብት ልማት ቢሮ",
  "አዲስ አበባ ፖሊስ ጠቅላይ መምሪያ",
  "ፋይናንስ ቢሮ",
  "ንግድ ቢሮ",
  "ትረንስፖርት ቢሮ",
  "ትራፊክ ማኔጅመንት ባለስልጣን",
  "ገቢዎች ቢሮ",
  "ወጣቶችና ስፖርት ቢሮ",
  "የኢቨስትምንተ ኮሚሽን",
  "የእሳትና አደጋ ስጋት ሥራ አመራር ኮሚሽን",
  "ዋና ኦዲተር መ/ቤት",
  "አዲስ አበባ ከተማ አስተዳደር ፍ/ቤት",
  "ታክስ ይግባኝ ኮሚሽን",
  "የካቲት 12 ሆስፒታል ሜዲካል ኮሌጅ",
  "ራስ ደስታ ዳምጠው ሆስፒታል",
  "ዘውዲቱ መታሰቢያ ሆስፒታል",
  "ዳግማዊ ሚኒሊክ ስፔሻላይዝድ ሆስፒታል",
  "ጋንዲ መታሰቢያ ሆስፒታል",
  "ጥሩነሽ ቤጂንግ ሆስፒታል",
  "ትላልቅ ፕሮጀክቶች ጽ/ቤት",
  "ስነ ምግባርና ፀረ-ሙስና ኮሚሽን",
  "መብራት አገልግሎት አስተዳደር ባለስልጣን",
  "መንግስት የልማት ድርጅቶች አስተዳደር ባለስልጣን",
  "ትምህርትና ስልጠና ጥራት ቁጥጥር ባለስላጣን",
  "መንግስት ንበረት አስተዳደር ባሰልጣን",
  "አሽከርካሪና ተሽከርካሪ ፈቃድና ቁጥጥር ባለስጣን",
  "መንገዶች ባለስልጣን",
  "አዲስ ሚዲያ ኔትዎርክ",
  "አዲስ አበባ ቄራዎች ድርጅት",
  "አዲስ አበባ ከተማ ሲቲ ባስ አገልግሎት",
  "አዲስ አበባ ቀላል ባቡር",
  "ከነማ ፋርማሲ ድርጅት",
  "ፓርኮች አስተዳደር ድርጅት",
  "ሲኒማ ቤቶች አስተዳደር",
  "ታላቁ ህዳሴ ግድብ ግንባታ ህዝባዊ ተሳትፎ አስተባባሪ ጽ/ቤት",
  "ኢግዚብሽን ማዕከልና ገብያ ልማት ድርጅት",
  "ህዝብ መዝናኛ ፓርኮች አስተዳደር ኮሮፖሬሽን",
];

export const certificate = {
  success: true,
  data: [
    {
      sector: "ICT and Innovation",
      "ፈንዳሜንታል ፕሮግራሚንግ": {
        male: 5,
        female: 7,
        sum: 12,
      },
      "አንድሮይድ ፕሮግራሚንግ": {
        male: 3,
        female: 4,
        sum: 7,
      },
      "ዳታ ሳይንስ": {
        male: 4,
        female: 6,
        sum: 10,
      },
      "አርቴፊሻል ኢንተለጀንስ": {
        male: 2,
        female: 5,
        sum: 7,
      },
      certified: {
        male: 10,
        female: 15,
        sum: 25,
      },
      fullyCertified: {
        male: 2,
        female: 3,
        sum: 5,
      },
    },
  ],
};

export const data2 = {
  success: true,
  data: [
    {
      sector: "አዲስ አበባ ከተማ ምክር ቤት",
      "ፈንዳሜንታል ፕሮግራሚንግ": { male: 15, female: 12, sum: 27 },
      "አንድሮይድ ፕሮግራሚንግ": { male: 10, female: 5, sum: 15 },
      "ዳታ ሳይንስ": { male: 6, female: 9, sum: 15 },
      "አርቴፊሻል ኢንተለጀንስ": { male: 4, female: 7, sum: 11 },
      certified: { male: 12, female: 10, sum: 22 },
      fullyCertified: { male: 6, female: 5, sum: 11 },
    },
    {
      sector: "ለአማራ ብሔራዊ ክልል መንግሥት",
      "ፈንዳሜንታል ፕሮግራሚንግ": { male: 18, female: 14, sum: 32 },
      "አንድሮይድ ፕሮግራሚንግ": { male: 9, female: 6, sum: 15 },
      "ዳታ ሳይንስ": { male: 7, female: 8, sum: 15 },
      "አርቴፊሻል ኢንተለጀንስ": { male: 5, female: 4, sum: 9 },
      certified: { male: 17, female: 12, sum: 29 },
      fullyCertified: { male: 9, female: 6, sum: 15 },
    },
    {
      sector: "ለኦሮሚያ ክልል መንግሥት",
      "ፈንዳሜንታል ፕሮግራሚንግ": { male: 21, female: 19, sum: 40 },
      "አንድሮይድ ፕሮግራሚንግ": { male: 11, female: 10, sum: 21 },
      "ዳታ ሳይንስ": { male: 10, female: 11, sum: 21 },
      "አርቴፊሻል ኢንተለጀንስ": { male: 7, female: 6, sum: 13 },
      certified: { male: 18, female: 15, sum: 33 },
      fullyCertified: { male: 8, female: 9, sum: 17 },
    },
    {
      sector: "ለቴክኖሎጂ ማዕከላዊ መምህራን ኮሌጅ",
      "ፈንዳሜንታል ፕሮግራሚንግ": { male: 13, female: 17, sum: 30 },
      "አንድሮይድ ፕሮግራሚንግ": { male: 5, female: 7, sum: 12 },
      "ዳታ ሳይንስ": { male: 6, female: 9, sum: 15 },
      "አርቴፊሻል ኢንተለጀንስ": { male: 4, female: 4, sum: 8 },
      certified: { male: 11, female: 14, sum: 25 },
      fullyCertified: { male: 5, female: 6, sum: 11 },
    },
    {
      sector: "ኢትዮ ቴሌኮም",
      "ፈንዳሜንታል ፕሮግራሚንግ": { male: 20, female: 13, sum: 33 },
      "አንድሮይድ ፕሮግራሚንግ": { male: 15, female: 10, sum: 25 },
      "ዳታ ሳይንስ": { male: 9, female: 8, sum: 17 },
      "አርቴፊሻል ኢንተለጀንስ": { male: 6, female: 5, sum: 11 },
      certified: { male: 19, female: 13, sum: 32 },
      fullyCertified: { male: 10, female: 9, sum: 19 },
    },
    {
      sector: "የግል መስክ ዲጂታል ካምፓኒዎች",
      "ፈንዳሜንታል ፕሮግራሚንግ": { male: 14, female: 10, sum: 24 },
      "አንድሮይድ ፕሮግራሚንግ": { male: 9, female: 6, sum: 15 },
      "ዳታ ሳይንስ": { male: 5, female: 5, sum: 10 },
      "አርቴፊሻል ኢንተለጀንስ": { male: 3, female: 4, sum: 7 },
      certified: { male: 12, female: 9, sum: 21 },
      fullyCertified: { male: 6, female: 5, sum: 11 },
    },
    {
      sector: "የአገልግሎት ተቋማት ሰነዶች",
      "ፈንዳሜንታል ፕሮግራሚንግ": { male: 12, female: 9, sum: 21 },
      "አንድሮይድ ፕሮግራሚንግ": { male: 7, female: 5, sum: 12 },
      "ዳታ ሳይንስ": { male: 6, female: 4, sum: 10 },
      "አርቴፊሻል ኢንተለጀንስ": { male: 3, female: 2, sum: 5 },
      certified: { male: 10, female: 8, sum: 18 },
      fullyCertified: { male: 4, female: 4, sum: 8 },
    },
    {
      sector: "የዩኒቨርሲቲ ሰራተኞች",
      "ፈንዳሜንታል ፕሮግራሚንግ": { male: 11, female: 13, sum: 24 },
      "አንድሮይድ ፕሮግራሚንግ": { male: 5, female: 6, sum: 11 },
      "ዳታ ሳይንስ": { male: 8, female: 7, sum: 15 },
      "አርቴፊሻል ኢንተለጀንስ": { male: 4, female: 3, sum: 7 },
      certified: { male: 13, female: 11, sum: 24 },
      fullyCertified: { male: 6, female: 7, sum: 13 },
    },
    {
      sector: "የኢንጂነሪንግ ድርጅቶች",
      "ፈንዳሜንታል ፕሮግራሚንግ": { male: 19, female: 8, sum: 27 },
      "አንድሮይድ ፕሮግራሚንግ": { male: 14, female: 3, sum: 17 },
      "ዳታ ሳይንስ": { male: 7, female: 6, sum: 13 },
      "አርቴፊሻል ኢንተለጀንስ": { male: 3, female: 2, sum: 5 },
      certified: { male: 16, female: 6, sum: 22 },
      fullyCertified: { male: 8, female: 3, sum: 11 },
    },
    {
      sector: "አዲስ አበባ ከተማ ምክር ቤት",
      "ፈንዳሜንታል ፕሮግራሚንግ": { male: 15, female: 12, sum: 27 },
      "አንድሮይድ ፕሮግራሚንግ": { male: 10, female: 5, sum: 15 },
      "ዳታ ሳይንስ": { male: 6, female: 9, sum: 15 },
      "አርቴፊሻል ኢንተለጀንስ": { male: 4, female: 7, sum: 11 },
      certified: { male: 12, female: 10, sum: 22 },
      fullyCertified: { male: 6, female: 5, sum: 11 },
    },
    {
      sector: "ለአማራ ብሔራዊ ክልል መንግሥት",
      "ፈንዳሜንታል ፕሮግራሚንግ": { male: 18, female: 14, sum: 32 },
      "አንድሮይድ ፕሮግራሚንግ": { male: 9, female: 6, sum: 15 },
      "ዳታ ሳይንስ": { male: 7, female: 8, sum: 15 },
      "አርቴፊሻል ኢንተለጀንስ": { male: 5, female: 4, sum: 9 },
      certified: { male: 17, female: 12, sum: 29 },
      fullyCertified: { male: 9, female: 6, sum: 15 },
    },
    {
      sector: "ለኦሮሚያ ክልል መንግሥት",
      "ፈንዳሜንታል ፕሮግራሚንግ": { male: 21, female: 19, sum: 40 },
      "አንድሮይድ ፕሮግራሚንግ": { male: 11, female: 10, sum: 21 },
      "ዳታ ሳይንስ": { male: 10, female: 11, sum: 21 },
      "አርቴፊሻል ኢንተለጀንስ": { male: 7, female: 6, sum: 13 },
      certified: { male: 18, female: 15, sum: 33 },
      fullyCertified: { male: 8, female: 9, sum: 17 },
    },
    {
      sector: "ለቴክኖሎጂ ማዕከላዊ መምህራን ኮሌጅ",
      "ፈንዳሜንታል ፕሮግራሚንግ": { male: 13, female: 17, sum: 30 },
      "አንድሮይድ ፕሮግራሚንግ": { male: 5, female: 7, sum: 12 },
      "ዳታ ሳይንስ": { male: 6, female: 9, sum: 15 },
      "አርቴፊሻል ኢንተለጀንስ": { male: 4, female: 4, sum: 8 },
      certified: { male: 11, female: 14, sum: 25 },
      fullyCertified: { male: 5, female: 6, sum: 11 },
    },
    {
      sector: "ኢትዮ ቴሌኮም",
      "ፈንዳሜንታል ፕሮግራሚንግ": { male: 20, female: 13, sum: 33 },
      "አንድሮይድ ፕሮግራሚንግ": { male: 15, female: 10, sum: 25 },
      "ዳታ ሳይንስ": { male: 9, female: 8, sum: 17 },
      "አርቴፊሻል ኢንተለጀንስ": { male: 6, female: 5, sum: 11 },
      certified: { male: 19, female: 13, sum: 32 },
      fullyCertified: { male: 10, female: 9, sum: 19 },
    },
    {
      sector: "የግል መስክ ዲጂታል ካምፓኒዎች",
      "ፈንዳሜንታል ፕሮግራሚንግ": { male: 14, female: 10, sum: 24 },
      "አንድሮይድ ፕሮግራሚንግ": { male: 9, female: 6, sum: 15 },
      "ዳታ ሳይንስ": { male: 5, female: 5, sum: 10 },
      "አርቴፊሻል ኢንተለጀንስ": { male: 3, female: 4, sum: 7 },
      certified: { male: 12, female: 9, sum: 21 },
      fullyCertified: { male: 6, female: 5, sum: 11 },
    },
    {
      sector: "የአገልግሎት ተቋማት ሰነዶች",
      "ፈንዳሜንታል ፕሮግራሚንግ": { male: 12, female: 9, sum: 21 },
      "አንድሮይድ ፕሮግራሚንግ": { male: 7, female: 5, sum: 12 },
      "ዳታ ሳይንስ": { male: 6, female: 4, sum: 10 },
      "አርቴፊሻል ኢንተለጀንስ": { male: 3, female: 2, sum: 5 },
      certified: { male: 10, female: 8, sum: 18 },
      fullyCertified: { male: 4, female: 4, sum: 8 },
    },
    {
      sector: "የዩኒቨርሲቲ ሰራተኞች",
      "ፈንዳሜንታል ፕሮግራሚንግ": { male: 11, female: 13, sum: 24 },
      "አንድሮይድ ፕሮግራሚንግ": { male: 5, female: 6, sum: 11 },
      "ዳታ ሳይንስ": { male: 8, female: 7, sum: 15 },
      "አርቴፊሻል ኢንተለጀንስ": { male: 4, female: 3, sum: 7 },
      certified: { male: 13, female: 11, sum: 24 },
      fullyCertified: { male: 6, female: 7, sum: 13 },
    },
    {
      sector: "የኢንጂነሪንግ ድርጅቶች",
      "ፈንዳሜንታል ፕሮግራሚንግ": { male: 19, female: 8, sum: 27 },
      "አንድሮይድ ፕሮግራሚንግ": { male: 14, female: 3, sum: 17 },
      "ዳታ ሳይንስ": { male: 7, female: 6, sum: 13 },
      "አርቴፊሻል ኢንተለጀንስ": { male: 3, female: 2, sum: 5 },
      certified: { male: 16, female: 6, sum: 22 },
      fullyCertified: { male: 8, female: 3, sum: 11 },
    },
    {
      sector: "አዲስ አበባ ከተማ ምክር ቤት",
      "ፈንዳሜንታል ፕሮግራሚንግ": { male: 15, female: 12, sum: 27 },
      "አንድሮይድ ፕሮግራሚንግ": { male: 10, female: 5, sum: 15 },
      "ዳታ ሳይንስ": { male: 6, female: 9, sum: 15 },
      "አርቴፊሻል ኢንተለጀንስ": { male: 4, female: 7, sum: 11 },
      certified: { male: 12, female: 10, sum: 22 },
      fullyCertified: { male: 6, female: 5, sum: 11 },
    },
    {
      sector: "ለአማራ ብሔራዊ ክልል መንግሥት",
      "ፈንዳሜንታል ፕሮግራሚንግ": { male: 18, female: 14, sum: 32 },
      "አንድሮይድ ፕሮግራሚንግ": { male: 9, female: 6, sum: 15 },
      "ዳታ ሳይንስ": { male: 7, female: 8, sum: 15 },
      "አርቴፊሻል ኢንተለጀንስ": { male: 5, female: 4, sum: 9 },
      certified: { male: 17, female: 12, sum: 29 },
      fullyCertified: { male: 9, female: 6, sum: 15 },
    },
    {
      sector: "ለኦሮሚያ ክልል መንግሥት",
      "ፈንዳሜንታል ፕሮግራሚንግ": { male: 21, female: 19, sum: 40 },
      "አንድሮይድ ፕሮግራሚንግ": { male: 11, female: 10, sum: 21 },
      "ዳታ ሳይንስ": { male: 10, female: 11, sum: 21 },
      "አርቴፊሻል ኢንተለጀንስ": { male: 7, female: 6, sum: 13 },
      certified: { male: 18, female: 15, sum: 33 },
      fullyCertified: { male: 8, female: 9, sum: 17 },
    },
    {
      sector: "ለቴክኖሎጂ ማዕከላዊ መምህራን ኮሌጅ",
      "ፈንዳሜንታል ፕሮግራሚንግ": { male: 13, female: 17, sum: 30 },
      "አንድሮይድ ፕሮግራሚንግ": { male: 5, female: 7, sum: 12 },
      "ዳታ ሳይንስ": { male: 6, female: 9, sum: 15 },
      "አርቴፊሻል ኢንተለጀንስ": { male: 4, female: 4, sum: 8 },
      certified: { male: 11, female: 14, sum: 25 },
      fullyCertified: { male: 5, female: 6, sum: 11 },
    },
    {
      sector: "ኢትዮ ቴሌኮም",
      "ፈንዳሜንታል ፕሮግራሚንግ": { male: 20, female: 13, sum: 33 },
      "አንድሮይድ ፕሮግራሚንግ": { male: 15, female: 10, sum: 25 },
      "ዳታ ሳይንስ": { male: 9, female: 8, sum: 17 },
      "አርቴፊሻል ኢንተለጀንስ": { male: 6, female: 5, sum: 11 },
      certified: { male: 19, female: 13, sum: 32 },
      fullyCertified: { male: 10, female: 9, sum: 19 },
    },
    {
      sector: "የግል መስክ ዲጂታል ካምፓኒዎች",
      "ፈንዳሜንታል ፕሮግራሚንግ": { male: 14, female: 10, sum: 24 },
      "አንድሮይድ ፕሮግራሚንግ": { male: 9, female: 6, sum: 15 },
      "ዳታ ሳይንስ": { male: 5, female: 5, sum: 10 },
      "አርቴፊሻል ኢንተለጀንስ": { male: 3, female: 4, sum: 7 },
      certified: { male: 12, female: 9, sum: 21 },
      fullyCertified: { male: 6, female: 5, sum: 11 },
    },
    {
      sector: "የአገልግሎት ተቋማት ሰነዶች",
      "ፈንዳሜንታል ፕሮግራሚንግ": { male: 12, female: 9, sum: 21 },
      "አንድሮይድ ፕሮግራሚንግ": { male: 7, female: 5, sum: 12 },
      "ዳታ ሳይንስ": { male: 6, female: 4, sum: 10 },
      "አርቴፊሻል ኢንተለጀንስ": { male: 3, female: 2, sum: 5 },
      certified: { male: 10, female: 8, sum: 18 },
      fullyCertified: { male: 4, female: 4, sum: 8 },
    },
    {
      sector: "የዩኒቨርሲቲ ሰራተኞች",
      "ፈንዳሜንታል ፕሮግራሚንግ": { male: 11, female: 13, sum: 24 },
      "አንድሮይድ ፕሮግራሚንግ": { male: 5, female: 6, sum: 11 },
      "ዳታ ሳይንስ": { male: 8, female: 7, sum: 15 },
      "አርቴፊሻል ኢንተለጀንስ": { male: 4, female: 3, sum: 7 },
      certified: { male: 13, female: 11, sum: 24 },
      fullyCertified: { male: 6, female: 7, sum: 13 },
    },
    {
      sector: "የኢንጂነሪንግ ድርጅቶች",
      "ፈንዳሜንታል ፕሮግራሚንግ": { male: 19, female: 8, sum: 27 },
      "አንድሮይድ ፕሮግራሚንግ": { male: 14, female: 3, sum: 17 },
      "ዳታ ሳይንስ": { male: 7, female: 6, sum: 13 },
      "አርቴፊሻል ኢንተለጀንስ": { male: 3, female: 2, sum: 5 },
      certified: { male: 16, female: 6, sum: 22 },
      fullyCertified: { male: 8, female: 3, sum: 11 },
    },
    {
      sector: "አዲስ አበባ ከተማ ምክር ቤት",
      "ፈንዳሜንታል ፕሮግራሚንግ": { male: 15, female: 12, sum: 27 },
      "አንድሮይድ ፕሮግራሚንግ": { male: 10, female: 5, sum: 15 },
      "ዳታ ሳይንስ": { male: 6, female: 9, sum: 15 },
      "አርቴፊሻል ኢንተለጀንስ": { male: 4, female: 7, sum: 11 },
      certified: { male: 12, female: 10, sum: 22 },
      fullyCertified: { male: 6, female: 5, sum: 11 },
    },
    {
      sector: "ለአማራ ብሔራዊ ክልል መንግሥት",
      "ፈንዳሜንታል ፕሮግራሚንግ": { male: 18, female: 14, sum: 32 },
      "አንድሮይድ ፕሮግራሚንግ": { male: 9, female: 6, sum: 15 },
      "ዳታ ሳይንስ": { male: 7, female: 8, sum: 15 },
      "አርቴፊሻል ኢንተለጀንስ": { male: 5, female: 4, sum: 9 },
      certified: { male: 17, female: 12, sum: 29 },
      fullyCertified: { male: 9, female: 6, sum: 15 },
    },
    {
      sector: "ለኦሮሚያ ክልል መንግሥት",
      "ፈንዳሜንታል ፕሮግራሚንግ": { male: 21, female: 19, sum: 40 },
      "አንድሮይድ ፕሮግራሚንግ": { male: 11, female: 10, sum: 21 },
      "ዳታ ሳይንስ": { male: 10, female: 11, sum: 21 },
      "አርቴፊሻል ኢንተለጀንስ": { male: 7, female: 6, sum: 13 },
      certified: { male: 18, female: 15, sum: 33 },
      fullyCertified: { male: 8, female: 9, sum: 17 },
    },
    {
      sector: "ለቴክኖሎጂ ማዕከላዊ መምህራን ኮሌጅ",
      "ፈንዳሜንታል ፕሮግራሚንግ": { male: 13, female: 17, sum: 30 },
      "አንድሮይድ ፕሮግራሚንግ": { male: 5, female: 7, sum: 12 },
      "ዳታ ሳይንስ": { male: 6, female: 9, sum: 15 },
      "አርቴፊሻል ኢንተለጀንስ": { male: 4, female: 4, sum: 8 },
      certified: { male: 11, female: 14, sum: 25 },
      fullyCertified: { male: 5, female: 6, sum: 11 },
    },
    {
      sector: "ኢትዮ ቴሌኮም",
      "ፈንዳሜንታል ፕሮግራሚንግ": { male: 20, female: 13, sum: 33 },
      "አንድሮይድ ፕሮግራሚንግ": { male: 15, female: 10, sum: 25 },
      "ዳታ ሳይንስ": { male: 9, female: 8, sum: 17 },
      "አርቴፊሻል ኢንተለጀንስ": { male: 6, female: 5, sum: 11 },
      certified: { male: 19, female: 13, sum: 32 },
      fullyCertified: { male: 10, female: 9, sum: 19 },
    },
    {
      sector: "የግል መስክ ዲጂታል ካምፓኒዎች",
      "ፈንዳሜንታል ፕሮግራሚንግ": { male: 14, female: 10, sum: 24 },
      "አንድሮይድ ፕሮግራሚንግ": { male: 9, female: 6, sum: 15 },
      "ዳታ ሳይንስ": { male: 5, female: 5, sum: 10 },
      "አርቴፊሻል ኢንተለጀንስ": { male: 3, female: 4, sum: 7 },
      certified: { male: 12, female: 9, sum: 21 },
      fullyCertified: { male: 6, female: 5, sum: 11 },
    },
    {
      sector: "የአገልግሎት ተቋማት ሰነዶች",
      "ፈንዳሜንታል ፕሮግራሚንግ": { male: 12, female: 9, sum: 21 },
      "አንድሮይድ ፕሮግራሚንግ": { male: 7, female: 5, sum: 12 },
      "ዳታ ሳይንስ": { male: 6, female: 4, sum: 10 },
      "አርቴፊሻል ኢንተለጀንስ": { male: 3, female: 2, sum: 5 },
      certified: { male: 10, female: 8, sum: 18 },
      fullyCertified: { male: 4, female: 4, sum: 8 },
    },
    {
      sector: "የዩኒቨርሲቲ ሰራተኞች",
      "ፈንዳሜንታል ፕሮግራሚንግ": { male: 11, female: 13, sum: 24 },
      "አንድሮይድ ፕሮግራሚንግ": { male: 5, female: 6, sum: 11 },
      "ዳታ ሳይንስ": { male: 8, female: 7, sum: 15 },
      "አርቴፊሻል ኢንተለጀንስ": { male: 4, female: 3, sum: 7 },
      certified: { male: 13, female: 11, sum: 24 },
      fullyCertified: { male: 6, female: 7, sum: 13 },
    },
    {
      sector: "የኢንጂነሪንግ ድርጅቶች",
      "ፈንዳሜንታል ፕሮግራሚንግ": { male: 19, female: 8, sum: 27 },
      "አንድሮይድ ፕሮግራሚንግ": { male: 14, female: 3, sum: 17 },
      "ዳታ ሳይንስ": { male: 7, female: 6, sum: 13 },
      "አርቴፊሻል ኢንተለጀንስ": { male: 3, female: 2, sum: 5 },
      certified: { male: 16, female: 6, sum: 22 },
      fullyCertified: { male: 8, female: 3, sum: 11 },
    },
  ],
};

export const data4 = {
  success: true,
  data: {
    summary: [
      {
        sector: "አዲስ አበባ ከተማ ምክር ቤት",
        plan: 2036432,
        certified: 100432,
        percentage: "4.93%",
      },
      {
        sector: "ወሎ ዞን ጤና ቢሮ",
        plan: 1500000,
        certified: 678900,
        percentage: "45.26%",
      },
      {
        sector: "አፄ ግዛት የትምህርት ቢሮ",
        plan: 800000,
        certified: 800000,
        percentage: "100.00%",
      },
      {
        sector: "አማራ ብሔራዊ ባንክ",
        plan: 950000,
        certified: 12500,
        percentage: "1.32%",
      },
      {
        sector: "አፄ የመሬት ምድብ",
        plan: 500000,
        certified: 225000,
        percentage: "45.00%",
      },
    ],
    data: [
      {
        sector: "አዲስ አበባ ከተማ ምክር ቤት",
        "ፈንዳሜንታል ፕሮግራሚንግ": { male: 30000, female: 40000, sum: 70000 },
        "አንድሮይድ ፕሮግራሚንግ": { male: 12000, female: 8000, sum: 20000 },
        "ዳታ ሳይንስ": { male: 5000, female: 3000, sum: 8000 },
        "አርቴፊሻል ኢንተለጀንስ": { male: 10000, female: 4000, sum: 14000 },
        certified: { male: 60000, female: 40432, sum: 100432 },
        fullyCertified: { male: 20000, female: 15000, sum: 35000 },
      },
      {
        sector: "ወሎ ዞን ጤና ቢሮ",
        "ፈንዳሜንታል ፕሮግራሚንግ": { male: 250000, female: 280000, sum: 530000 },
        "አንድሮይድ ፕሮግራሚንግ": { male: 50000, female: 30000, sum: 80000 },
        "ዳታ ሳይንስ": { male: 20000, female: 30000, sum: 50000 },
        "አርቴፊሻል ኢንተለጀንስ": { male: 5000, female: 5000, sum: 10000 },
        certified: { male: 180000, female: 498900, sum: 678900 },
        fullyCertified: { male: 90000, female: 150000, sum: 240000 },
      },
      {
        sector: "አፄ ግዛት የትምህርት ቢሮ",
        "ፈንዳሜንታል ፕሮግራሚንግ": { male: 300000, female: 400000, sum: 700000 },
        "አንድሮይድ ፕሮግራሚንግ": { male: 50000, female: 50000, sum: 100000 },
        "ዳታ ሳይንስ": { male: 0, female: 0, sum: 0 },
        "አርቴፊሻል ኢንተለጀንስ": { male: 0, female: 0, sum: 0 },
        certified: { male: 400000, female: 400000, sum: 800000 },
        fullyCertified: { male: 300000, female: 300000, sum: 600000 },
      },
      {
        sector: "አማራ ብሔራዊ ባንክ",
        "ፈንዳሜንታል ፕሮግራሚንግ": { male: 1000, female: 1000, sum: 2000 },
        "አንድሮይድ ፕሮግራሚንግ": { male: 2000, female: 500, sum: 2500 },
        "ዳታ ሳይንስ": { male: 3000, female: 1000, sum: 4000 },
        "አርቴፊሻል ኢንተለጀንስ": { male: 2000, female: 1000, sum: 3000 },
        certified: { male: 7000, female: 5500, sum: 12500 },
        fullyCertified: { male: 2000, female: 1500, sum: 3500 },
      },
      {
        sector: "አፄ የመሬት ምድብ",
        "ፈንዳሜንታል ፕሮግራሚንግ": { male: 120000, female: 130000, sum: 250000 },
        "አንድሮይድ ፕሮግራሚንግ": { male: 40000, female: 30000, sum: 70000 },
        "ዳታ ሳይንስ": { male: 10000, female: 10000, sum: 20000 },
        "አርቴፊሻል ኢንተለጀንስ": { male: 15000, female: 15000, sum: 30000 },
        certified: { male: 100000, female: 125000, sum: 225000 },
        fullyCertified: { male: 80000, female: 80000, sum: 160000 },
      },
    ],
  },
};
